### ISSUE TITLE
kaplan_markov function is broken

### ISSUE THREAD

**Issue by umbernhard** [pbstark/SHANGRLA#13]
The kaplan_markov function currently doesn't work, as it tries to do 
```any(x < 0)``` while x is a list in `find_p_values`. 

Wrapping the definition of `d`  with `np.array(...)` in `find_p_values` on [line 1442](https://github.com/pbstark/SHANGRLA/blob/main/Code/assertion_audit_utils.py#L1412) of `assertion_audit_utils` fixes this issue.

**Comment by pbstark** [comment]
Thank you! I don't see the issue on line 1442, but I do see it on lines 1000 and 1036. Changed to any(xx<0 for xx in x). PR pending.
