### ISSUE TITLE
Impact of RuntimeWarning: overflow encountered in Notebook and tests?

### ISSUE THREAD

**Issue by nealmcb** [pbstark/SHANGRLA#2]
In the published notebook [assertion-RLA.ipynb](https://github.com/pbstark/SHANGRLA/blob/master/Code/assertion-RLA.ipynb) there are some warnings displayed:

Find initial sample size

```
/opt/tljh/user/lib/python3.6/site-packages/numpy/core/fromnumeric.py:90: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
```

Find measured risks for all assertions
```
/opt/shared/Code/assertion_audit_utils.py:984: RuntimeWarning: overflow encountered in double_scalars
  a[k+1,j] += 0 if j==0 else (1-c[k])*(j/(k+1))*a[k,j-1]
/opt/shared/Code/assertion_audit_utils.py:983: RuntimeWarning: overflow encountered in double_scalars
  a[k+1,j] = -c[k]*((k+1-j)/(k+1))*a[k,j]
/opt/shared/Code/assertion_audit_utils.py:1048: RuntimeWarning: invalid value encountered in multiply
  mart_vec = np.multiply(Y_norm,integrals)
```

I also see these among the warnings displayed when running `pytest assertion_audit_utils.py`.

Should we worry about these? Fix them? Suppress them somehow?

**Comment by pbstark** [comment]
I think they arise (algebraically) only when the p-value is essentially zero (they are overflows of the reciprocal of the p-value) for the KMart risk-measuring function. The recursive integration algorithm is so far the mot stable I've found (this one is devised by Steve Evans, UC Berkeley). I'm reluctant to suppress the message, but I don't think it signifies a problem.

**Comment by pbstark** [comment]
Resolved by latest merge.

**Comment by nealmcb** [comment]
Good to hear it.  Do you mean the merge of https://github.com/pbstark/SHANGRLA/pull/5?

**Comment by pbstark** [comment]
Yes; I believe that solves the problem. Please holler if you find otherwise.
