### ISSUE TITLE
Where is ballot_comparison module?

### ISSUE THREAD

**Issue by nealmcb** [pbstark/SHANGRLA#3]
The tests and notebooks related to SUITE and hybrid audits fail for lack of a `ballot_comparison` module. I presume that a dependency is missing.

```
# python Code/suite_tools.py
Traceback (most recent call last):
  File "Code/suite_tools.py", line 11, in <module>
    from ballot_comparison import ballot_comparison_pvalue
ModuleNotFoundError: No module named 'ballot_comparison'
```
Note also that there are some extraneous files like
 `Code/.ipynb_checkpoints/hybrid-audit-example-3-checkpoint.ipynb`
 that should be removed and avoided via an addition to `.gitignore`.

**Comment by pbstark** [comment]
suite_tools.py is not used in the SHANGRLA code; I developed new ballot comparison risk-measuring functions for this. I'll remove it from the dependencies. Thanks for the checks and reports!
