### ISSUE TITLE
Looking for oc_cvrs.zip

### ISSUE THREAD

**Issue by JohnLCaron** [pbstark/SHANGRLA#87]
Hi All:

Im working with Vanessa Teague et al, to understand SHANGRLA and evaluate porting it.

Im trying to run examples/OC_example.ipynb in SHANGRLA python repo. It references RLA files not in the repo, apparently from the Orange County 2022 election:

'cvr_file': '/Users/amanda/Downloads/oc_cvrs.zip',
#'cvr_file': '/Users/Jake/Desktop/oc_cvrs.zip',

Are these available somewhere that I can download?

If not, is there another example data set I can use to run a complete SHANGRLA workflow?

Thanks,
John  (https://github.com/JohnLCaron)

**Comment by pbstark** [comment]
Hi John--

Alas, we don't have permission to post the OC data behind that notebook. But data behind [this example ](https://github.com/pbstark/SHANGRLA/blob/main/examples/assertion-RLA.ipynb) are in the repository.

Thank you for your interest in SHANGRLA!

Cheers,
Philip

**Comment by JohnLCaron** [comment]
Hi Philip: 

Thanks for your response. I wanted to start with a non-IRV use case. But perhaps I can use PLURALITY on the same data?

Regrds,
John
