### ISSUE TITLE
Welford's Algorithm in NonnegMean

### ISSUE THREAD

**Issue by fleverest** [pbstark/SHANGRLA#88]
I compared the implementation of Welford's algorithm for calculating the running mean implemented in `NonnegMean.shrink_trunc` to an [existing implementation online](https://github.com/a-mitani/welford), and I found some discrepancy in the results.

The specific lines I'm referring to can be found here:
https://github.com/pbstark/SHANGRLA/blob/38ffc5db8a91df2f21950c08661a115f09a4d1c6/shangrla/core/NonnegMean.py#L301-L308

Extracting this code into a short function, we have:

```python
import numpy as np

def shrink_trunc_welford(x: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        j = np.arange(1, len(x) + 1)
        mj = [x[0]]
        sdj = [0]
        for i, xj in enumerate(x[1:]):
            mj.append(mj[-1] + (xj - mj[-1]) / (i + 1))
            sdj.append(sdj[-1] + (xj - mj[-2]) * (xj - mj[-1]))
        sdj = np.sqrt(sdj / j)
        return mj, sdj
```

Then, a quick test:

```python
x = np.array([1.5,2.5,1.7,1.0,1.2,2.1,1.4,1.8])
m, sd = shrink_trunc_welford(x)
print(m)
# [1.5, 2.5, 2.1, 1.7333333333333334, 1.6, 1.7000000000000002, 1.6500000000000001, 1.6714285714285715]
print(np.mean(x))
# 1.65
```

It seems the currently implemented running mean overshoots the true mean of the sample.

I'm not sure whether this is expected or not, but I compared this to an existing implementation in the `welford` package on pypi:

```python
from welford import Welford

welford = Welford()
m = []
for xi in x:
    welford.add(xi)
    m.append(float(welford.mean))
print(m)
# [1.5, 2.0, 1.9, 1.6749999999999998, 1.5799999999999998, 1.6666666666666665, 1.6285714285714283, 1.65]
```

This implementation does not overshoot the sample mean. If this is not intended, let me know and I should be able to tweak the implementation accordingly quite easily.

Also, it appears the algorithm is implemented again in agrapa, although the code looks to be slightly different (perhaps calculating variance rather than sd):

https://github.com/pbstark/SHANGRLA/blob/38ffc5db8a91df2f21950c08661a115f09a4d1c6/shangrla/core/NonnegMean.py#L419-L426

**Comment by pbstark** [comment]
Good catch--Thank you! I thought I had tested it but apparently not. It goes sideways at the 2nd datum. Please fix the implementation if you have time. Probably makes sense to have a Welford function that shrink_trunk and agrapa both call. 

Best wishes,
Philip
